name: crumbl_menu

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 0,1'  # Runs Sunday and Monday at 6 am PT (13:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BOT_NAME: "crumbl_menu"
      BOT_PATH: "./bots/crumbl_menu"
      PYTHONPATH: "${{ github.workspace }}"  # Set the PYTHONPATH to the project root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.BOT_PATH }}/requirements.txt

      - name: Run the scraper
        run: |
          python ${{ env.BOT_PATH }}/main.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Pull latest changes before committing
        run: |
          git config pull.rebase false
          git pull origin main

      - name: Commit updated timeseries
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.BOT_PATH }}/src/data/
          git commit -m "Updated data" -a --allow-empty --author="stiles <stiles@users.noreply.github.com>"

      - name: Push changes to main branch
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}