name: example

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 GMT

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r ./bots/example/requirements.txt

      - name: Run the bot
        run: bash ./bots/example/src/runbot.sh

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: python ./utils/s3_upload.py ./bots/example/src/data example
