name: tiktok_followers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 GMT

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BOT_NAME: "tiktok_followers"
      BOT_PATH: "./bots/tiktok_followers"
      DATA_DIR: "./src/data"
      PYTHONPATH: "${{ github.workspace }}"  # Set the PYTHONPATH to the project root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.BOT_PATH }}/requirements.txt

      - name: Run the scraper
        run: |
          python ${{ env.BOT_PATH }}/main.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          PYTHONPATH: "${{ github.workspace }}"  # Ensure PYTHONPATH is set for this step

      - name: Commit updated timeseries
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.DATA_DIR }}/
          git commit -m "Update timeseries data" -a --allow-empty --author="stiles <stiles@users.noreply.github.com>"

      - name: Push changes to main branch
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}